# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
     - '.github/workflows/**'
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Dispatch an event to the consumer repo
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
         token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
         repository: mayashavin/nuxt-blog-template
         event-type: merge-content
         client-payload: '{"message": "New blog posted!"}'

